name: haveno
description: "An interface for interacting with the Haveno Network"
publish_to: 'none' 

version: 0.0.2

environment:
  sdk: '>=3.4.3 <4.0.0'

homepage: https://haveno.com
repository: https://github.com/KewbitXMR/haveno-plus
issue_tracker: https://github.com/username/haveno-plus/issues
license: MIT

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  socks5_proxy: ^1.0.6
  grpc: ^3.0.0
  protobuf: ^3.1.0
  provider: ^6.0.0
  path_provider: ^2.0.11
  multi_select_flutter: ^4.1.3
  logging: ^1.0.1
  flutter_chat_ui: ^1.6.14
  flutter_chat_types: ^3.6.2
  uuid: ^3.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  timeline_tile: ^2.0.0
  fixnum: ^1.1.0
  intl: ^0.17.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/haveno-logo.png