# Haveno App extends the features of Haveno, supporting mobile devices and more.
# Copyright (C) 2024 Kewbit (https://kewbit.org)
# Source Code: https://git.haveno.com/haveno/haveno-app.git
#
# Author: Kewbit
#    Website: https://kewbit.org
#    Contact Email: me@kewbit.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: haveno_app
description: "Haveno Multi-Platform Application"
license: AGPL-3
repository: https://git.haveno.com/haveno/haveno-app

version: 0.4.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  git: ^2.3.0 
  haveno: ^3.0.4
  socks5_proxy: ^2.1.0
  flutter_socks_proxy: ^0.0.3
  provider: ^6.0.0
  path_provider: ^2.1.4
  multi_select_flutter: ^4.1.3
  uuid: ^4.4.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  fixnum: ^1.1.0
  intl: ^0.19.0
  badges: ^3.1.2
  cryptography: ^2.7.0
  file: ^7.0.0
  path: ^1.9.0
  http2: ^2.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
#  url_launcher: ^6.3.0
  archive: ^4.0.7
#  connectivity_plus: ^6.0.5
#  internet_connection_checker_plus: ^2.5.1
  interactive_chart: ^0.3.5
  chatview: ^2.1.1
  #local_auth: ^2.3.0 ## To do faceid etc
  package_info_plus: ^8.0.2
  #workmanager: ^0.5.2  ## Probably needed for ios to check for messafes every 15 mins
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.2.1
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  timezone: ^0.10.1
  crypto: ^3.0.5
  pointycastle: ^4.0.0
  onboarding: ^4.0.2
  collection: ^1.18.0
  dropdown_search: ^5.0.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: ^0.5.32
  tray_manager: ^0.5.0
  window_manager: ^0.5.0
  background_downloader: ^9.2.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  permission_handler: ^12.0.0
  teledart: ^0.6.1
  #cs_monero: ^1.0.0-pre.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  min_sdk_android: 21
  adaptive_icon_background: "#303030"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  android:
    generate: true
    image_path: "assets/icon/app_icon.png"
    adaptive_icon_background: "#303030"
    adaptive_icon_foreground: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  ios: false
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#303030"
  image: assets/icon/app_icon.png
  branding: assets/icon/app_icon.png
  branding_bottom_padding: 24
  color_dark: "#303030"
  image_dark: assets/icon/app_icon.png
  branding_dark: assets/icon/app_icon.png

  android_12:
    image: assets/icon/app_icon.png
    icon_background_color: "#303030"
    image_dark: assets/icon/app_icon.png
    icon_background_color_dark: "#303030"

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/versions.json
    - assets/config/default/torrc
    - assets/getting-started-logo.png
    - assets/arbitration-logo.png
    - assets/haveno-logo.png
    - assets/tor-logo.png
    - assets/monero_logo.png
    - assets/tether_logo.png
    - assets/bitcoin_logo.png
    - assets/icon/app_icon.png
    - assets/icon/app_icon.ico
    - assets/icon/app_icon_smaller.png